/**
 * 把 tsdown 构建的 IIFE bundle 转成可被 Metro require 的 CJS 模块。
 *
 * 输入: dist/index.js (tsdown 产物, IIFE 格式)
 * 输出: dist/bundle.js (CJS 模块, 导出字符串)
 *
 * 参考 Joplin 的 copyAssets.ts 模式:
 * https://github.com/laurent22/joplin/blob/main/packages/app-mobile/tools/buildInjectedJs/copyAssets.ts
 */
import { readFileSync, writeFileSync } from "fs";

const bundleJs = readFileSync("dist/index.js", "utf-8");

writeFileSync(
  "dist/bundle.js",
  `// Auto-generated by scripts/codegen.mjs — do not edit\nmodule.exports = ${JSON.stringify(bundleJs)};\n`,
);

console.log(`✓ dist/bundle.js generated (${(bundleJs.length / 1024).toFixed(0)} KB)`);
