---
rust:
  directory: ./rust/mobile-core
  manifestPath: Cargo.toml

android:
  targets:
    - arm64-v8a

bindings:
  cpp: cpp/generated
  ts: src/generated

noOverwrite:
  - android/build.gradle
  - package.json
  - SwarmnoteCore.podspec
