//! Pairing — device-to-device handshake for establishing a trusted mesh.
//!
//! Wraps the `PairingManager` surface reachable via `AppCore::pairing()`. All
//! methods fail with [`FfiError::NetworkNotRunning`] if the P2P node is down,
//! so the RN host should await `start_network()` before calling anything here.
//!
//! Flow for an outbound pair (this device initiates):
//! ```text
//!   1. peer generates code (its side calls generate_pairing_code)
//!    ↓
//!   2. this device calls lookup_device_by_code(code) → peerId + osInfo
//!    ↓
//!   3. this device calls request_pairing(peerId, Code{code}, remoteOsInfo)
//!    ↓
//!   4. on Success: PairedDeviceAdded event fires on both sides
//! ```
//!
//! Flow for an inbound pair (this device accepts):
//! ```text
//!   1. PairingRequestReceived event fires with pendingId
//!    ↓
//!   2. RN prompts user, then calls respond_pairing_request(pendingId, accept)
//! ```

use std::time::SystemTime;

use swarmnote_core::api::{PairedDeviceInfo, PairingCodeInfo};
use swarmnote_core::protocol::{
    OsInfo, PairingMethod, PairingRefuseReason, PairingResponse,
};

use crate::app::UniffiAppCore;
use crate::error::FfiError;

// ── Records ──────────────────────────────────────────────────

#[derive(Debug, Clone, uniffi::Record)]
pub struct UniffiOsInfo {
    pub name: Option<String>,
    pub hostname: String,
    pub os: String,
    pub platform: String,
    pub arch: String,
}

impl From<OsInfo> for UniffiOsInfo {
    fn from(o: OsInfo) -> Self {
        Self {
            name: o.name,
            hostname: o.hostname,
            os: o.os,
            platform: o.platform,
            arch: o.arch,
        }
    }
}

impl From<UniffiOsInfo> for OsInfo {
    fn from(o: UniffiOsInfo) -> Self {
        Self {
            name: o.name,
            hostname: o.hostname,
            os: o.os,
            platform: o.platform,
            arch: o.arch,
        }
    }
}

#[derive(Debug, Clone, uniffi::Record)]
pub struct UniffiPairingCodeInfo {
    /// 6-digit code the remote side types in.
    pub code: String,
    pub created_at: SystemTime,
    pub expires_at: SystemTime,
}

impl From<PairingCodeInfo> for UniffiPairingCodeInfo {
    fn from(c: PairingCodeInfo) -> Self {
        Self {
            code: c.code,
            created_at: c.created_at.into(),
            expires_at: c.expires_at.into(),
        }
    }
}

#[derive(Debug, Clone, uniffi::Enum)]
pub enum UniffiPairingMethod {
    /// Code-based pair (the pairer types a 6-digit code generated by the
    /// pairee — the normal flow).
    Code { code: String },
    /// Implicit pair, no code step. Reserved for future "auto-pair
    /// discovered by nearby LAN scan" UX.
    Direct,
}

impl From<UniffiPairingMethod> for PairingMethod {
    fn from(m: UniffiPairingMethod) -> Self {
        match m {
            UniffiPairingMethod::Code { code } => PairingMethod::Code { code },
            UniffiPairingMethod::Direct => PairingMethod::Direct,
        }
    }
}

impl From<PairingMethod> for UniffiPairingMethod {
    fn from(m: PairingMethod) -> Self {
        match m {
            PairingMethod::Code { code } => UniffiPairingMethod::Code { code },
            PairingMethod::Direct => UniffiPairingMethod::Direct,
        }
    }
}

#[derive(Debug, Clone, uniffi::Enum)]
pub enum UniffiPairingRefuseReason {
    UserRejected,
    CodeExpired,
    CodeInvalid,
}

impl From<PairingRefuseReason> for UniffiPairingRefuseReason {
    fn from(r: PairingRefuseReason) -> Self {
        match r {
            PairingRefuseReason::UserRejected => UniffiPairingRefuseReason::UserRejected,
            PairingRefuseReason::CodeExpired => UniffiPairingRefuseReason::CodeExpired,
            PairingRefuseReason::CodeInvalid => UniffiPairingRefuseReason::CodeInvalid,
        }
    }
}

#[derive(Debug, Clone, uniffi::Enum)]
pub enum UniffiPairingResponse {
    Success,
    Refused { reason: UniffiPairingRefuseReason },
}

impl From<PairingResponse> for UniffiPairingResponse {
    fn from(r: PairingResponse) -> Self {
        match r {
            PairingResponse::Success => UniffiPairingResponse::Success,
            PairingResponse::Refused { reason } => UniffiPairingResponse::Refused {
                reason: reason.into(),
            },
        }
    }
}

#[derive(Debug, Clone, uniffi::Record)]
pub struct UniffiPairedDeviceInfo {
    pub peer_id: String,
    pub name: Option<String>,
    pub hostname: String,
    pub os: String,
    pub platform: String,
    pub arch: String,
    pub paired_at: SystemTime,
    pub last_seen: Option<SystemTime>,
    pub is_online: Option<bool>,
    pub rtt_ms: Option<u64>,
}

impl From<PairedDeviceInfo> for UniffiPairedDeviceInfo {
    fn from(p: PairedDeviceInfo) -> Self {
        Self {
            peer_id: p.peer_id,
            name: p.name,
            hostname: p.hostname,
            os: p.os,
            platform: p.platform,
            arch: p.arch,
            paired_at: p.paired_at.into(),
            last_seen: p.last_seen.map(Into::into),
            is_online: p.is_online,
            rtt_ms: p.rtt_ms,
        }
    }
}

/// Result of resolving a pairing code against the DHT: the publisher's peer
/// id + the OS info they embedded in the record. `listen_addrs` are NOT
/// surfaced to RN — the core already registered them with the libp2p swarm
/// as a side effect, so the subsequent `request_pairing` call can dial
/// directly.
#[derive(Debug, Clone, uniffi::Record)]
pub struct UniffiDeviceByCodeResult {
    pub peer_id: String,
    pub os_info: UniffiOsInfo,
}

// ── Methods on UniffiAppCore ─────────────────────────────────

#[uniffi::export]
impl UniffiAppCore {
    /// Generate a 6-digit pairing code, publish the device's OsInfo +
    /// listen addrs under that code to the DHT, and return the code + its
    /// expiry window. Only one code is active at a time — calling this
    /// again overwrites the previous code.
    pub async fn generate_pairing_code(
        &self,
        expires_in_secs: u64,
    ) -> Result<UniffiPairingCodeInfo, FfiError> {
        let pm = self.inner.pairing().await?;
        Ok(pm.generate_code(expires_in_secs).await?.into())
    }

    /// Resolve a pairing code via DHT lookup. Returns the publisher's peer
    /// id + OS info. Must be followed by `request_pairing(...)` to actually
    /// send the pairing request.
    pub async fn lookup_device_by_code(
        &self,
        code: String,
    ) -> Result<UniffiDeviceByCodeResult, FfiError> {
        let pm = self.inner.pairing().await?;
        let (peer_id, record) = pm.get_device_by_code(&code).await?;
        Ok(UniffiDeviceByCodeResult {
            peer_id,
            os_info: record.os_info.into(),
        })
    }

    /// Send a pairing request to the given peer. On `Success`, the remote
    /// device is persisted as paired and a `PairedDeviceAdded` event fires.
    /// On `Refused`, the reason indicates whether the user rejected or the
    /// code expired/was wrong.
    pub async fn request_pairing(
        &self,
        peer_id: String,
        method: UniffiPairingMethod,
        remote_os_info: Option<UniffiOsInfo>,
    ) -> Result<UniffiPairingResponse, FfiError> {
        let pm = self.inner.pairing().await?;
        let resp = pm
            .request_pairing(&peer_id, method.into(), remote_os_info.map(Into::into))
            .await?;
        Ok(resp.into())
    }

    /// Accept or reject an incoming pairing request (delivered via the
    /// `PairingRequestReceived` event). On accept, the pairing is finalized
    /// and a `PairedDeviceAdded` event fires.
    pub async fn respond_pairing_request(
        &self,
        pending_id: u64,
        accept: bool,
    ) -> Result<(), FfiError> {
        let pm = self.inner.pairing().await?;
        pm.handle_pairing_request(pending_id, accept).await?;
        Ok(())
    }

    /// Snapshot of every paired device. Returns `Vec::new()` if P2P is not
    /// running (since the paired-devices cache is populated on node start);
    /// that way the settings screen can render an empty list instead of
    /// surfacing an error.
    pub async fn list_paired_devices(&self) -> Vec<UniffiPairedDeviceInfo> {
        let Ok(pm) = self.inner.pairing().await else {
            return Vec::new();
        };
        pm.get_paired_devices()
            .into_iter()
            .map(UniffiPairedDeviceInfo::from)
            .collect()
    }

    /// Remove a device from the paired set. Fires `PairedDeviceRemoved` on
    /// success. Removes from both the in-memory cache and `devices.db`.
    pub async fn unpair_device(&self, peer_id: String) -> Result<(), FfiError> {
        let pm = self.inner.pairing().await?;
        pm.unpair(&peer_id).await.map_err(Into::into)
    }
}
