// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-swarmnote-core.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "SwarmnoteCoreSpec.h"

@interface SwarmnoteCore : NSObject <NativeSwarmnoteCoreSpec>
#else
#import <React/RCTBridgeModule.h>

@interface SwarmnoteCore : NSObject <RCTBridgeModule>
#endif

@end