// Generated by uniffi-bindgen-react-native
#include "react-native-swarmnote-core.h"
#include "generated\mobile_core.hpp"

namespace swarmnotecore {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMobileCore::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}